basics/blueprints/onebp/views/bpview.py
from flask import render_template, Blueprint


bpview = Blueprint("bpview", __name__)

@bpview.route("/auth")
def authhome():
	return render_template("auth/authhome.html")

@bpview.route("/auth/login")
def authlogin():
	return render_template("auth/login.html")

basics/blueprints/onebp/templates/index.html
{% extends "layout.html" %}

{% block headarea %}
Welcome to Flask Blueprint page
{% endblock %}

{% block content %} 
<div>Welcome to Blueprint home</div>

{% endblock %}
{% block footarea %} {% endblock %}

basics/blueprints/onebp/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> Flask Blueprint Demo</title>
	{{ bootstrap.load_css() }}
	{{ bootstrap.load_js() }}

</head>
<body>
{% block navarea %}
    <h1>Welcome to the Index Page</h1>
    <a href="{{ url_for('bphome') }}" class="btn btn-primary">home</a>
    <a href="{{ url_for('bpview.authhome') }}" class="btn btn-primary">Go to Auth Home</a>
    <a href="{{ url_for('bpview.authlogin') }}" class="btn btn-primary">Go to Login</a>
{% endblock %}
{% block content %} {% endblock %}
{% block footarea %} {% endblock %}
</body>
</html>

basics/templates/form.html
{% extends "index.html" %}

{% macro upper(text) %}
    
{% endmacro %}

{% block form1 %}
    <form action="/submitform1" method="post">
        <input type="text" name="name" />
        <input type="password" name="password" />
        <input type="submit" value="提交" />
    </form>
{% endblock %}

{% block form2 %}
	<p> data 1</p>
	<ul>
		{% for item in items.data1 %}
			<li>{{ item | capitalize  }} </li>
		{% endfor %}
	</ul>
	<p>data 2</p>
    <ul>
        {% for item in items.data2 %}
            {% if item.is_active %}
                <li>{{ item }}</li>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}

basics/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
</head>
<body>
	<h3><a href="{{url_for('useforms')}}">show forms</a></h3>
	<h3><a href="{{url_for('args1', name='river')}}">args to dict()</a></h3>

	<div>

		<p> 
			{% raw %}
			運算式 {{ 2+2 }} : {{ 2+2 }}</p>
			{% endraw %}
	</div>
	<div>
		<H3>Form display</H3>
		<div>
			form 1
			{% block form1 %}{% endblock %}
		</div>
		<div>
			form 2
			{% block form2 %}{% endblock %}
		</div>
	</div>
</body>
</html>